import React from 'react';
import { Box, Button, Heading, Text, VStack } from '@chakra-ui/react';
import Sidebar from './Sidebar';

const SavedContent = () => {
  const savedCaptions = [
    {
      topic: 'Skipli is launching SkipliAI',
      captions: [
        'Introducing Skipli AI - the smarter, faster way to craft compelling content! Experience all the magic of AI-driven writing assistance and get great results with fewer headaches. #AI #ContentMarketing #Content',
        'Say goodbye to writer\'s block! #SkipliAI is now available to make creating attention-grabbing content easier than ever! Get ready to take your social media game to the next level with #AI #SocialMedia #Writing'
      ]
    },
    {
      topic: 'Idea generated by AI 2',
      captions: [
        'Introducing Skipli AI - the smarter, faster way to craft compelling content! Experience all the magic of AI-driven writing assistance and get great results with fewer headaches. #AI #ContentMarketing #Content',
        'Say goodbye to writer\'s block! #SkipliAI is now available to make creating attention-grabbing content easier than ever! Get ready to take your social media game to the next level with #AI #SocialMedia #Writing'
      ]
    }
  ];

  return (
    <Box display="flex" width="100vw" height="100vh">
      <Sidebar currentPath="/profile" />
      <Box flex="1" padding="2rem" overflowY="auto">
        <VStack spacing={6} align="start" maxWidth="600px" margin="0 auto">
          <Heading>Saved Content</Heading>
          {savedCaptions.map((item, index) => (
            <Box key={index} width="100%">
              <Heading as="h2" size="md" my={4}>{item.topic}</Heading>
              <VStack spacing={4} align="stretch">
                {item.captions.map((caption, idx) => (
                  <Box key={idx} borderWidth={1} borderRadius={8} p={4} mb={4}>
                    <Text mb={4}>{caption}</Text>
                    <Box display="flex" justifyContent="space-between">
                      <Button colorScheme="teal">Share</Button>
                      <Button variant="outline">Unsave</Button>
                    </Box>
                  </Box>
                ))}
              </VStack>
            </Box>
          ))}
        </VStack>
      </Box>
    </Box>
  );
};

export default SavedContent;